version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=admin123
    command: redis-server --requirepass admin123
    volumes:
      - redis_data:/data

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/.Dockerfile
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - 3005:3005
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  redis_data:
    driver: local