version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=admin123
    command: redis-server --requirepass admin123
    volumes:
      - redis_data:/data

  api-gateway:
    image: api-gateway:latest
    ports:
      - 3000:3000
    environment:
      - RMQ_URL=amqp://admin:admin@localhost:5672
    depends_on:
      - rabbitmq
  user-service:
    image: user-service:latest
    ports:
      - 3006:3006
    environment:
      - RMQ_URL=amqp://admin:admin@localhost:5672

volumes:
  redis_data:
