enum RBMQ_SERVICES {
  AUTH = 'AUTH_SERVICE',
  USER = 'USER_SERVICE',
  LOAN = 'LOAN_SERVICE',
  INVESTMENT = 'INVESTMENT_SERVICE',
  REPAYMENT = 'REPAYMENT_SERVICE',
  NOTIFICATION = 'NOTIFICATION_SERVICE',
  PAYMENT = 'PAYMENT_SERVICE',
  REPORT = 'REPORT_SERVICE',
}
enum RBMQ_QUEUES {
  AUTH = 'AUTH_QUEUE',
  USER = 'USER_QUEUE',
  LOAN = 'LOAN_QUEUE',
  INVESTMENT = 'INVESTMENT_QUEUE',
  REPAYMENT = 'REPAYMENT_QUEUE',
  NOTIFICATION = 'NOTIFICATION_QUEUE',
  PAYMENT = 'PAYMENT_QUEUE',
  REPORT = 'REPORT_QUEUE',
}

export { RBMQ_SERVICES, RBMQ_QUEUES };
