name: Test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        ref:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: npx prisma generate --schema=apps/user-service/prisma/schema.prisma
      - run: npm run test
